// types.js
const INCREMENT_COUNT = 'INCREMENT';
const DECREMENT_COUNT = 'DECREMENT';

const REQUEST_SUBREDDIT_JSON = 'REQUEST_SUBREDDIT_JSON';
const RECEIVE_SUBREDDIT_JSON = 'RECEIVE_SUBREDDIT_JSON';

export default {
    INCREMENT_COUNT,
    DECREMENT_COUNT,
    REQUEST_SUBREDDIT_JSON,
    RECEIVE_SUBREDDIT_JSON
}